parameters:
  rust: stable
  allow_fail: false
  setup: []
  fail_all: false

jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.rust, 'stable') }}:
    ${{ if eq(parameters.fail_all, 'true') }}:
      displayName: cargo clippy -- -D warnings
    ${{ if ne(parameters.fail_all, 'true') }}:
      displayName: cargo clippy
  ${{ if ne(parameters.rust, 'stable') }}:
    ${{ if eq(parameters.fail_all, 'true') }}:
      displayName: cargo +${{ parameters.rust }} clippy -- -D warnings
    ${{ if ne(parameters.fail_all, 'true') }}:
      displayName: cargo +${{ parameters.rust }} clippy
  continueOnError: ${{ parameters.allow_fail }}
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: install-rust.yml
      parameters:
        rust: ${{ parameters.rust }}
        setup: ${{ parameters.setup }}
        components:
          - clippy
    - ${{ if eq(parameters.fail_all, 'true') }}:
      - script: cargo clippy --all -- -D warnings
        displayName: Run strict clippy
    - ${{ if ne(parameters.fail_all, 'true') }}:
      - script: cargo clippy --all
        displayName: Run strict clippy
