jobs:
 - job: enable
   pool:
     vmImage: ubuntu-16.04
   steps:
     - script: "echo ___${CHECK}___"
     - script: "[[ -n $CHECK ]] && [[ ! $CHECK == '$('* ]] && echo '##vso[task.setvariable variable=has_secret;isOutput=true]true'"
       name: secret_check
       env:
         CHECK: ${{ parameters.codecov_token }}
 - job: tarpaulin
   dependsOn: enable
   condition: and(succeeded(), eq('true', dependencies.enable.outputs['secret_check.has_secret']))
   displayName: tarpaulin
   pool:
     vmImage: ubuntu-16.04
   container:
     image: xd009642/tarpaulin:latest
     options: --security-opt seccomp=unconfined
   steps:
     - script: cargo tarpaulin --out Xml
       displayName: Run tarpaulin
     - script: bash <(curl -s https://codecov.io/bash)
       displayName: Upload results to codecov
       env:
         CODECOV_TOKEN: ${{ parameters.codecov_token }}
