jobs:
 - ${{ if ne(format('{0}', parameters.codecov_tokens), '') }}
   - job: tarpaulin
     displayName: tarpaulin
     pool:
       vmImage: ubuntu-16.04
     container:
       image: xd009642/tarpaulin:latest
       options: --security-opt seccomp=unconfined
     steps:
       - script: cargo tarpaulin --out Xml
         displayName: Run tarpaulin
       - script: bash <(curl -s https://codecov.io/bash)
         displayName: Upload results to codecov
         env:
           CODECOV_TOKEN: ${{ parameters.codecov_token }}
