jobs:
 - job: tarpaulin
   # note that we use '' as the first argument to coerce the second to a string
   # this is necessary in the cases where latter is an unset variable (== null)
   condition: ne('', ${{ parameters.codecov_token }})
   displayName: tarpaulin
   pool:
     vmImage: ubuntu-16.04
   container:
     image: xd009642/tarpaulin:latest
     options: --security-opt seccomp=unconfined
   steps:
     - script: cargo tarpaulin --out Xml
       displayName: Run tarpaulin
     - script: bash <(curl -s https://codecov.io/bash)
       displayName: Upload results to codecov
       env:
         CODECOV_TOKEN: ${{ parameters.codecov_token }}
