jobs:
  - template: rustfmt.yml
    parameters:
      name: rustfmt
  - template: rustfmt.yml
    parameters:
      name: rustfmt_beta
      rust: beta
      allow_fail: true
  - template: cargo-clippy.yml
    parameters:
      name: clippy
  - template: cargo-clippy.yml
    parameters:
      name: clippy_beta
      rust: beta
      allow_fail: true
