parameters:
  minrust: 1.32.0 # Rust 2018 with uniform paths

jobs:
 # This represents the minimum Rust version supported.
 # Tests are not run as tests may require newer versions of rust.
 - template: azure/cargo-check.yml
   parameters:
     name: minrust
     rust: ${{ parameters.minrust }}
 - template: azure/test.yml
   parameters:
     name: cargo_test_stable
     cross: true # also test on Windows and macOS
 - template: azure/test.yml
   parameters:
     name: cargo_test_beta
     rust: beta
 - template: azure/test.yml
   parameters:
     name: cargo_test_nightly
     rust: nightly
     allow_fail: true
