stages:
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: $(CODECOV_TOKEN_SECRET)
 # should work without code coverage token
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "nosecret_"
     codecov_token: $(DOES_NOT_EXIST)
 # also test with various other configuration changes
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     benches: true
     prefix: "opts_"

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
