stages:
 # check that templates from master still work
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "master_"
     codecov_token: $(CODECOV_TOKEN_SECRET)
 # check that _current_ templates work
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: $(CODECOV_TOKEN_SECRET)

resources:
  repositories:
    - repository: templates
      type: github
      name: jonhoo/rusty-pipes
      endpoint: jonhoo
