stages:
  - stage: primary
    jobs:
      - template: default.yml
        parameters:
          minrust: 1.34.0 # integer atomics
          codecov_token: $(CODECOV_TOKEN_SECRET)
          env:
            ENV_IS_SET: true
          setup:
            - script: touch src/setup.rs
              displayName: touch src/setup.rs
  # should work without code coverage token
  - stage: bad_coverage_token
    dependsOn: []
    jobs:
      - template: default.yml
        parameters:
          minrust: 1.34.0
          codecov_token: $(DOES_NOT_EXIST)
          env:
            ENV_IS_SET: true
          setup:
            - script: touch src/setup.rs
              displayName: touch src/setup.rs
  # visual check that cross: false is indeed Linux-only
  - stage: no_cross
    dependsOn: []
    jobs:
      - template: default.yml
        parameters:
          minrust: 1.34.0
          cross: false
          env:
            ENV_IS_SET: true
          setup:
            - script: touch src/setup.rs
              displayName: touch src/setup.rs
