stages:
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: $(CODECOV_TOKEN_SECRET)
     test_features: ci
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # should work without code coverage token
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "nosecret_"
     codecov_token: $(DOES_NOT_EXIST)
     test_features: ci
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # also test with various other configuration changes
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     benches: true
     test_features: ci
     test_ignored: true
     single_threaded: true
     nightly_coverage: true
     nightly_feature: 'opt_in'
     prefix: "opts_"
     check_all_features: false
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # and on nightly-only stages
 - template: azure/nightly-stages.yml
   parameters:
     benches: true
     test_features: ci,opt_in
     test_ignored: true
     single_threaded: true
     prefix: "nightly_"
     check_all_features: false
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # test binary-focused stages (no min rust version test)
 - template: azure/stages.yml
   parameters:
     minrust: false
     prefix: "bin_"
     test_features: ci
     envs:
       ENV_IS_SET: true
     setup:
       - script: touch src/setup.rs
 # test no features
 - template: azure/stages.yml
   parameters:
     minrust: false
     codecov_token: $(CODECOV_TOKEN_SECRET)
     prefix: "nofeat_"
     envs:
       ENV_IS_SET: true
       ALLOW_NO_FEATURES: true
     setup:
       - script: touch src/setup.rs
