stages:
 # check that templates from master still work
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "master_"
     codecov_token: $(CODECOV_TOKEN_SECRET)
 # check that _current_ templates work
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: $(CODECOV_TOKEN_SECRET)
 # even without code coverage token
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "nosecret_"
     codecov_token: $(DOES_NOT_EXIST)
 # we should also not display coverage if it's not been set up
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "noci_"
 # test binary-focused stages (no min rust version test)
 - template: azure/stages.yml
   parameters:
     minrust: false
     prefix: "bin_"

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
