stages:
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: $(CODECOV_TOKEN_SECRET)
 # should work without code coverage token
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "nosecret_"
     codecov_token: $(DOES_NOT_EXIST)
 # we should also not display coverage if it's not been set up
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "noci_"

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
