stages:
 # check that templates from master still work
 - template: azure/stages.yml@templates
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "master_"
     codecov_token: variables['Secret.CODECOV_TOKEN_SECRET']
 # check that _current_ templates work
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     codecov_token: variables['Secret.CODECOV_TOKEN_SECRET']
 # even without code coverage token
 - template: azure/stages.yml
   parameters:
     minrust: 1.34.0 # integer atomics
     prefix: "noci_"
     codecov_token: variables['DOES_NOT_EXIST']

resources:
  repositories:
    - repository: templates
      type: github
      name: jonhoo/rusty-pipes
      endpoint: jonhoo
